//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMMachine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string EID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Midinitial { get; set; }
        public string gender { get; set; }
        public string street { get; set; }
        public string city { get; set; }
    }
}
